version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "src/dotnet-web-react-vite-template.Web/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "tests/dotnet-web-react-vite-template.Web.Tests/"
    schedule:
      interval: "weekly"
